### ISSUE TITLE
UnboundLocalError: local variable 'nmap_command' referenced before assignment

### ISSUE THREAD

**Issue by williamoliveira** [cloudflare/flan#16] opened 2019-11-22 17:04 UTC
```
~/p/flan (master|✚1) $ make start
docker run --name flan_1574442140 -v /home/projects/flan/shared:/shared flan_scan
Traceback (most recent call last):
  File "/output_report.py", line 225, in <module>
    main()
  File "/output_report.py", line 221, in main
    create_latex(nmap_command, start_date)
UnboundLocalError: local variable 'nmap_command' referenced before assignment
sed: /shared/reports/report_2019.11.22-17.02.tex: No such file or directory
sed: /shared/reports/report_2019.11.22-17.02.tex: No such file or directory

```

**Comment by victorbordo** [comment] 2019-11-22 17:59
I'm seeing this error too. Leaving the default config ips `1.1.1.1` and `8.8.8.8` and adding an ip below them starts the scan successfully. Try reproducing it by removing the default ips from the config `shared/ips.txt` and adding a single ip address.

**Comment by nadinelyab** [comment] 2019-11-22 18:15
I think this is caused by adding an empty line to `shared/ips.txt` . I'have pushed a fix for this. Please let me know if that worked for you.

**Comment by victorbordo** [comment] 2019-11-22 19:20
Looks like that fixed it. Thanks @nadinelyab.

**Closed** 2019-11-22 19:52 UTC
