### ISSUE TITLE
TimeoutError: [Errno 110] Operation timed out

### ISSUE THREAD

**Issue by bbrendon** [cloudflare/flan#19] opened 2019-11-22 19:04 UTC
Errors and no results directory created.

```

==============NEXT SERVICE FINGERPRINT (SUBMIT INDIVIDUALLY)==============
SF-Port8082-TCP:V=7.70%T=SSL%I=7%D=11/22%Time=5DD82E1C%P=x86_64-alpine-lin
SF:ux-musl%r(GenericLines,37,"HTTP/1\.1\x20400\x20Bad\x20Request\r\nSec-We
SF:bSocket-Version:\x2013\r\n\r\n")%r(GetRequest,37,"HTTP/1\.1\x20400\x20B
SF:ad\x20Request\r\nSec-WebSocket-Version:\x2013\r\n\r\n")%r(HTTPOptions,3
SF:7,"HTTP/1\.1\x20400\x20Bad\x20Request\r\nSec-WebSocket-Version:\x2013\r
SF:\n\r\n");
Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel

Read data files from: /usr/bin/../share/nmap
Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
# Nmap done at Fri Nov 22 18:52:31 2019 -- 256 IP addresses (23 hosts up) scanned in 2470.12 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1133, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1178, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python3.5/http/client.py", line 1129, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python3.5/http/client.py", line 944, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.5/http/client.py", line 887, in send
    self.connect()
  File "/usr/local/lib/python3.5/http/client.py", line 1279, in connect
    super().connect()
  File "/usr/local/lib/python3.5/http/client.py", line 859, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/local/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/output_report.py", line 225, in <module>
    main()
  File "/output_report.py", line 221, in main
    create_latex(nmap_command, start_date)
  File "/output_report.py", line 163, in create_latex
    + '\\\\ \hline \end{tabular}  '
  File "/output_report.py", line 121, in get_description
    cve_json = json.loads(urllib.urlopen(url).read().decode("utf-8"))
  File "/usr/local/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/local/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Operation timed out>
sed: /shared/reports/report_2019.11.22-17.02.tex: No such file or directory
sed: /shared/reports/report_2019.11.22-17.02.tex: No such file or directory
sed: /shared/reports/report_2019.11.22-17.02.tex: No such file or directory


# ls -l shared/
total 12
-rw-r--r-- 1 root root   40 Nov 22 09:01 ips.txt
drwxr-xr-x 2 root root 4096 Nov 22 09:00 reports
drwxr-xr-x 3 root root 4096 Nov 22 09:02 xml_files
#

```

**Comment by root360-AndreasUlm** [comment] 2019-11-25 14:05
It seems that you are running flan in an environment that cannot connect to the internet to fetch the CVE information.
The exception is caused by https://github.com/cloudflare/flan/blob/master/output_report.py#L121 as the HTTP request to https://raw.githubusercontent.com/ times out.

This most likely is caused by issues with your internet connection, iptables setup, docker configuration or proxy configuration.

**Comment by nadinelyab** [comment] 2019-11-25 23:59
Yes what @root360-AndreasUlm is saying is correct. @bbrendon I will close this out as this is likely not an issue with Flan Scan itself. Let me know if you find out more about your specific configuration. Thanks!

**Closed** 2019-11-25 23:59 UTC
